steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mlops-vale/mlops-example1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mlops-vale/mlops-example1']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'mlops-example1', '--image=gcr.io/mlops-vale/mlops-example1', '--region=us-central1', '--platform=managed']

options:
  logging: CLOUD_LOGGING_ONLY  # Para enviar logs solo a Cloud Logging
